version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_DB: holiday_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: holiday_db
      DB_USER: postgres
      DB_PASSWORD: password
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
